### PR TITLE
Added more powered roadtypes to ROAD

### PR DESCRIPTION
**Pull request by Gadg8eer**
Still working on this, give me a bit.

### CODE REVIEW

**Comment by jfkuayue** [comment]
Hello. Why did you disable unstandardised types in roadtypetable?

**Comment by Gadg8eer** [comment]
> Hello. Why did you disable unstandardised types in roadtypetable?

That actually has a very good reason, if my memory serves me right: Each roadtype you define in the table adds to the total number of types, regardless of if it's defined in any other way. Whereas adding alternate_roadtype_list (which doesn't require the roadtype table) and defining only absolutely necessary roadtypes as having a powered_roadtype_list with a switch to only activate if if another roadtype set defines it can alleviate some of that issue, if used in combination with standard labels.

**Comment by Gadg8eer** [comment]
>> Hello. Why did you disable unstandardised types in roadtypetable?

> That actually has a very good reason, if my memory serves me right: Each roadtype you define in the table adds to the total number of types, regardless of if it's defined in any other way. Whereas adding alternate_roadtype_list (which doesn't require the roadtype table) and defining only absolutely necessary roadtypes as having a powered_roadtype_list with a switch to only activate if if another roadtype set defines it can alleviate some of that issue, if used in combination with standard labels.

Um, I hope that's okay? I wasn't trying to offend you or cause any drama, just help expidite other people's projects since I can't draw OpenTTD stuff worth crap and nobody liked me "recycling" their work. It seems to be a curse at this point that everyone finds a reason to hate me.

**Comment by jfkuayue** [comment]
> Um, I hope that's okay? I wasn't trying to offend you or cause any drama, just help expidite other people's projects since I can't draw OpenTTD stuff worth crap and nobody liked me "recycling" their work. It seems to be a curse at this point that everyone finds a reason to hate me.

Hello. It is okay. By the way, I also have Asperger's. And someone on the forums had reported errors in your grf:
[](https://www.tt-forums.net/viewtopic.php?p=1265176#p1265176)
Still, it is better to "cite" the author and painter of original GRFs. Better still is to draw and code your own stuff. I also draw too little, mainly doing coding stuff, but each time I fork or fix one GRF, I make it at least functional, and "cite" the original author in an obvious place. JF Ratt Roads is also forked from Auz Ratt Roads.

**Comment by Gadg8eer** [comment]
> > Um, I hope that's okay? I wasn't trying to offend you or cause any drama, just help expidite other people's projects since I can't draw OpenTTD stuff worth crap and nobody liked me "recycling" their work. It seems to be a curse at this point that everyone finds a reason to hate me.
> 
> Hello. It is okay. By the way, I also have Asperger's. And someone on the forums had reported errors in your grf: Still, it is better to "cite" the author and painter of original GRFs. Better still is to draw and code your own stuff. I also draw too little, mainly doing coding stuff, but each time I fork or fix one GRF, I make it at least functional, and "cite" the original author in an obvious place. JF Ratt Roads is also forked from Auz Ratt Roads.

Well I can't draw worth crap (at least, not for OpenTTD, my graphics always look terrible in-game if I try to do them from scratch) but I have never made a grf without at least giving some sort of credit, I swear.

Also, did you try to post a link? I'm banned from the forums but I should be able to see it without logging in if you can repost it; you never actually posted the URL?

**Comment by jfkuayue** [comment]
> Also, did you try to post a link? I'm banned from the forums but I should be able to see it without logging in if you can repost it; you never actually posted the URL?

https://www.tt-forums.net/viewtopic.php?p=1265176

**Pull request closed without merging**
